[package]
name = "ergothic_example"
version = "0.1.0"
authors = ["Cap. Hindsight <hindsight@yandex.ru>"]

[dependencies]
pretty_env_logger = "0.2.3"
rand = "0.5.3"

[dependencies.ergothic]
path = "../ergothic"
