[package]
name = "ergothic"
version = "0.1.0"
authors = ["Cap. Hindsight <hindsight@yandex.ru>"]

[dependencies]
bson = "0.10.0"
log = "0.4.3"
mongodb = "0.3.8"
serde = "1.0.69"
serde_derive = "1.0.69"
